### ISSUE TITLE
Upgrade to react-scripts 5.0.0 and react 17.0.2

### ISSUE THREAD

**Issue by jrhunter84** [fb55/nth-check#111]
I'm trying to upgrade react on my app and I'm getting this warning from npm:
nth-check  <2.0.1
Severity: moderate
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@3.0.1, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          Depends on vulnerable versions of resolve-url-loader
          node_modules/react-scripts

Any solutions would be greatly appreciated!

**Comment by fb55** [comment]
`npm audit fix --force`?

**Comment by rulrok** [comment]
It would be more benefitial if the package would release 2.0.1 CVE as a backport fix 1.0.3

![image](https://user-images.githubusercontent.com/3097987/151623548-a6849800-d94f-45f0-9482-d788a323c53b.png)

**Comment by AlonNavon** [comment]
Hey @rulrok ,

We're part of a startup called Seal Security that mitigates software vulnerabilities in older open source versions by backporting/creating standalone security patches - enabling more straightforward remediation in cases like this. We created an `nth-check 1.02-sp1` that's vulnerability-free. As with all of our patches, it's open-source and available for free.

If relevant, check out [our GitHub repo](https://github.com/seal-community/patches/tree/main/npm/nth-check/1.0.2/sp1) if you wish to learn more.

Please feel free to reach us at [info@seal.security](mailto:info@seal.security) if you have any requests/questions.
