### ISSUE TITLE
npm giving high severity vulnerability  while using it in react.js 

### ISSUE THREAD

**Issue by deepakdubey8756** [fb55/nth-check#218]
Hi everyone,
I am using react-typing-animation which depends on this package and npm is giving me high severity vulnerability warning -  "Insufficient Regular Expression Complexity in nth-check" while using it.
I am unable to fix the problem. Please help.
![vulnerabilittyIssue](https://user-images.githubusercontent.com/85337607/171545290-fbc0c2ec-1ab4-4cef-80e4-64e1a87d839b.png)

**Comment by fb55** [comment]
As the note says, this is patched in current versions of this library.

**Comment by G-Rath** [comment]
@fb55 would you be open to backporting the fix to the v1 branch? I'm happy to put in the work, if you would be happy to review & release it

**Comment by fb55** [comment]
@G-Rath I appreciate the offer, but I don't want to maintain several releases. As long as you aren't parsing user-supplied strings, there is no harm in ignoring this warning.

**Comment by G-Rath** [comment]
@fb55 unfortunately we build bespoke apps for many clients, and for some we're not allowed to just ignore these warnings 😞

**Comment by AlonNavon** [comment]
Hey @G-Rath,

We're part of a startup called Seal Security that mitigates software vulnerabilities in older open source versions by backporting/creating standalone security patches - enabling more straightforward remediation in cases like this. We created an `nth-check 1.02-sp1` that's vulnerability-free. As with all of our patches, it's open-source and available for free.

If relevant, check out [our GitHub repo](https://github.com/seal-community/patches/tree/main/npm/nth-check/1.0.2/sp1) if you wish to learn more, or start using our [app](https://app.sealsecurity.io).

Please feel free to reach us at [info@seal.security](mailto:info@seal.security) if you have any requests/questions.
