### ISSUE TITLE
node_modules cannot find compile.ts, index.ts, parse.ts but the files are in the dependency library. 

### ISSUE THREAD

**Issue by nanaboat1** [fb55/nth-check#274]
#### Description
My typescript react app is not downloading compile.ts, index.ts and parse.ts files from this dependency to work correctly and instead is displaying warnings from node_modules.

#### Screenshots
<img width="817" alt="Screen Shot 2022-08-22 at 7 21 04 AM" src="https://user-images.githubusercontent.com/33593752/185944384-b8ec77f9-a53f-4e99-ad7c-c2d3ebf6014f.png">

#### Platform 
MacOS, 
React -v 5.0.1
Typescript latest

**Comment by fb55** [comment]
That directory contains .js files 🙂

**Comment by nanaboat1** [comment]
Well, the compiler error says it is supposed to find or either download .ts files but the .ts files is not being downloaded from the url provided but its not being downloaded from that directory and also, I tried tracing to that url and it is giving me a 404 HTTP Error.
<img width="1130" alt="Screen Shot 2022-08-22 at 6 01 14 PM" src="https://user-images.githubusercontent.com/33593752/186045494-300a0e99-11ad-48a5-a63c-8faf60588597.png">

**Comment by fb55** [comment]
I'm not sure where that path comes from, as the map does contain the whole paths: https://unpkg.com/browse/nth-check@2.1.1/lib/esm/parse.js.map. It seems like the `sourceRoot` in your screenshot is cut off at some point, given that it also doesn't include the full git hash.

This is likely a shortcoming of source-map-loader — please check in there!
