### ISSUE TITLE
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr

### ISSUE THREAD

**Issue by abhayindusnet** [fb55/nth-check#466]
# npm audit report

nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@2.1.3, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          node_modules/react-scripts

6 high severity vulnerabilities
![nth-check issue](https://github.com/fb55/nth-check/assets/5045327/11ae21df-61cf-4b6d-b312-73e84bd98805)

How to fix these vulnerabilities ? I am using the below dependencies

"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.2.1",
    "@fortawesome/free-regular-svg-icons": "^6.2.1",
    "@fortawesome/free-solid-svg-icons": "^6.2.1",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@reduxjs/toolkit": "^1.9.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^0.27.2",
    "base-64": "^1.0.0",
    "bootstrap": "^5.2.1",
    "canada": "^0.1.0",
    "clientjs": "^0.2.1",
    "encode-utf8": "^2.0.0",
    "env-cmd": "^10.1.0",
    "formik": "^2.2.9",
    "i18next": "^22.4.6",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "papaparse": "^5.3.2",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-bootstrap": "^2.5.0",
    "react-datepicker": "^4.11.0",
    "react-datetime-picker": "^5.0.3",
    "react-dom": "^18.2.0",
    "react-i18next": "^12.1.1",
    "react-modal": "^3.16.1",
    "react-paginate": "^8.1.4",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.3.0",
    "react-scripts": "^5.0.1",
    "react-search-autocomplete": "^8.3.1",
    "react-switch": "^7.0.0",
    "reactstrap": "^9.1.5",
    "redux": "^4.2.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "styled-components": "^5.3.6",
    "utf8": "^3.0.0",
    "web-vitals": "^2.1.4",
    "webfontloader": "^1.6.28",
    "yup": "^0.32.11"
  },

**Comment by fb55** [comment]
So... upgrade?
