### ISSUE TITLE
getting issue with nth check while doing an npm audit can some anybudday help me with solving this issue

### ISSUE THREAD

**Issue by aruningole70** [fb55/nth-check#523]
nth-check  <2.0.1
Severity: high
Inefficient Regular Expression Complexity in nth-check - github repo
fix available via `npm audit fix --force`
Will install react-scripts@2.1.3, which is a breaking change
node_modules/svgo/node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          node_modules/react-scripts

**Comment by fb55** [comment]
Bump your deps 🙂
