### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [fb55/nth-check#8]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by fb55** [comment]
There is a contact at the bottom of the README. Feel free to open a PR!

Also, you can find my email address on feedic.com, should you not hear back from Tidelift.

**Comment by JamieSlome** [comment]
@fb55 - also feel free to check it out directly [here](https://huntr.dev/bounties/8cf8cc06-d2cf-4b4e-b42c-99fafb0b04d0/).

**Comment by markhughes** [comment]
@fb55 can you bump this on your other packages? e.g. https://github.com/fb55/css-select

**Comment by fb55** [comment]
@markhughes This is already covered by the version range of these packages. Doesn't a `npm audit --fix` fix this for you?
